build:
	mkdir -p functions
	GOOS=linux GOARCH=amd64 GO111MODULE=auto GOBIN=${PWD}/functions go get ./...
	GOOS=linux GOARCH=amd64 GO111MODULE=auto GOBIN=${PWD}/functions go install ./...

build-mac:
	mkdir -p functions
	GO111MODULE=auto go list ./...
	GO111MODULE=auto go get ./...
	GO111MODULE=auto go install ./...