[build]
  command = "make build"
  publish = "./"
  functions = "functions"

[build.environment]
  GO_VERSION = "1.17"


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"